Repository goorm-engineers4/people_of_delivery, pull requests merged in 2025-07, with the labels that each got.

#2 :rocket: 스프링 프로젝트 생성
  .gitattributes
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/example/cloudfour/peopleofdelivery/PeopleofdeliveryApplication.java
  src/main/resources/application.yml
  src/test/java/com/example/cloudfour/peopleofdelivery/PeopleofdeliveryApplicationTests.java
Labels: ⚙ Setting

#4 :sparkles: feat: - application.yml에 postgre 연결 - docker-compose.yml에 postgre 설정
  docker-compose.yml
  src/main/resources/application.yml
Labels: ✨ Feature

#13 ✨ feat: BaseEntity 생성
  src/main/java/com/example/cloudfour/peopleofdelivery/PeopleofdeliveryApplication.java
  src/main/java/com/example/cloudfour/peopleofdelivery/global/entity/BaseEntity.java
Labels: ✨ Feature

#15 ✨ [FEAT] BaseEntity 수정
  src/main/java/com/example/cloudfour/peopleofdelivery/global/entity/BaseEntity.java
Labels: ✨ Feature

#20 ✨ [FEAT] 주요 엔티티 생성
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/cart/entity/Cart.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/cartitem/entity/CartItem.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/order/entity/Order.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/order/entity/OrderHistory.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/order/enums/OrderStatus.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/order/enums/OrderType.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/order/enums/ReceiptType.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/orderitem/entity/OrderItem.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/payment/entity/Payment.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/payment/entity/PaymentHistory.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/payment/enums/PaymentStatus.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/region/entity/Region.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/review/entity/Review.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/user/entity/User.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/user/enums/Role.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/useraddress/entity/UserAddress.java
  src/main/java/com/example/cloudfour/peopleofdelivery/global/ai/entity/AiLog.java
  src/test/java/com/example/cloudfour/peopleofdelivery/domain/useraddress/entity/UserAddressTest.java
Labels: ✨ Feature

#16 ✨ [FEAT] 메뉴 관련 엔티티 생성
  .gitignore
  docker-compose.yml
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/entity/Menu.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/entity/MenuCategory.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/entity/MenuOption.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/entity/MenuStatus.java
Labels: ✨ Feature

#26 ✨ [FEAT] 엔티티 전체 연관관계 매핑, builder 수정
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/cart/entity/Cart.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/cartitem/entity/CartItem.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/entity/Menu.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/entity/MenuCategory.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/entity/MenuOption.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/enums/MenuStatus.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/order/entity/Order.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/order/entity/OrderHistory.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/orderitem/entity/OrderItem.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/payment/entity/Payment.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/payment/entity/PaymentHistory.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/region/entity/Region.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/review/entity/Review.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/store/entity/Store.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/store/entity/StoreCategory.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/user/entity/User.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/useraddress/entity/UserAddress.java
  src/main/java/com/example/cloudfour/peopleofdelivery/global/ai/entity/AiLog.java
  src/main/java/com/example/cloudfour/peopleofdelivery/global/entity/BaseEntity.java
Labels: ✨ Feature

#28 ✨ [FEAT] 엔티티 에러 코드
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/cart/exception/CartErrorCode.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/cart/exception/CartException.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/cartitem/exception/CartItemErrorCode.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/cartitem/exception/CartItemException.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/exception/MenuCategoryErrorCode.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/exception/MenuCategoryException.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/exception/MenuErrorCode.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/exception/MenuException.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/exception/MenuOptionErrorCode.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/exception/MenuOptionException.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/order/exception/OrderErrorCode.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/order/exception/OrderException.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/order/exception/OrderHistoryErrorCode.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/order/exception/OrderHistoryException.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/orderitem/exception/OrderItemErrorCode.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/orderitem/exception/OrderItemException.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/payment/exception/PaymentErrorCode.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/payment/exception/PaymentException.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/payment/exception/PaymentHistoryErrorCode.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/payment/exception/PaymentHistoryException.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/region/exception/RegionErrorCode.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/region/exception/RegionException.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/review/exception/ReviewErrorCode.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/review/exception/ReviewException.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/store/exception/StoreCategoryErrorCode.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/store/exception/StoreCategoryException.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/store/exception/StoreErrorCode.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/store/exception/StoreException.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/user/exception/UserErrorCode.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/user/exception/UserException.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/useraddress/exception/UserAddressErrorCode.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/useraddress/exception/UserAddressException.java
  src/main/java/com/example/cloudfour/peopleofdelivery/global/ai/exception/AiLogErrorCode.java
  src/main/java/com/example/cloudfour/peopleofdelivery/global/ai/exception/AiLogException.java
Labels: ✨ Feature

#32 📝 [DOCS] docker-compose, gitignore 재업로드
  .gitignore
  docker-compose.yml
Labels: 📃 Docs

#35 ✨ [FEAT] 리뷰 엔티티 MVC 완성
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/review/controller/ReviewController.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/review/converter/ReviewConverter.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/review/dto/ReviewRequestDTO.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/review/dto/ReviewResponseDTO.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/review/entity/Review.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/review/repository/ReviewRepository.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/review/service/command/ReviewCommandService.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/review/service/command/ReviewCommandServiceImpl.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/review/service/query/ReviewQueryService.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/review/service/query/ReviewQueryServiceImpl.java
Labels: ✨ Feature

#41 ✨ [FEAT] 주문 엔티티 컨트롤러 구현
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/order/controller/OrderController.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/order/dto/OrderRequestDTO.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/order/dto/OrderResponseDTO.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/order/repository/OrderRepository.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/order/service/command/OrderCommandServiceImpl.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/order/service/query/OrderQueryServiceImpl.java
Labels: ✨ Feature

#46 🔨 [REFACTOR] 리뷰 서비스 추상화 제거
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/review/controller/ReviewController.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/review/service/command/ReviewCommandService.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/review/service/command/ReviewCommandServiceImpl.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/review/service/query/ReviewQueryService.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/review/service/query/ReviewQueryServiceImpl.java
Labels: 🔨 Refactor

#54 ✨ [FEAT] 장바구니 관련 컨트롤러 구현
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/auth/service/AuthService.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/cart/controller/CartController.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/cart/converter/CartConverter.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/cart/dto/CartRequestDTO.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/cart/dto/CartResponseDTO.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/cart/entity/Cart.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/cart/exception/CartErrorCode.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/cart/repository/CartRepository.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/cart/service/command/CartCommandService.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/user/enums/Role.java
Labels: ✨ Feature

#55 ✨ [FEAT] 장바구니 아이템 관련 컨트롤러 구현
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/cartitem/controller/CartItemController.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/cartitem/converter/CartItemConverter.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/cartitem/dto/CartItemRequestDTO.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/cartitem/dto/CartItemResponseDTO.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/cartitem/service/command/CartItemCommandService.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/cartitem/service/query/CartItemQueryService.java
Labels: ✨ Feature

#53 ✨ [FEAT] 메뉴 관련 엔티티 MVC 구현
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/controller/MenuController.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/converter/MenuConverter.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/dto/MenuRequestDTO.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/dto/MenuResponseDTO.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/entity/Menu.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/repository/MenuCategoryRepository.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/repository/MenuOptionRepository.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/repository/MenuRepository.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/service/command/MenuCommandServiceImpl.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/service/query/MenuQueryServiceImpl.java
Labels: ✨ Feature

#62 🔨 refactor : import 경로 수정
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/region/entity/Region.java
  src/test/java/com/example/cloudfour/peopleofdelivery/domain/TestFixtureFactory.java
Labels: ✨ Feature

#64 🔨 fix : UserAddress 패키지 삭제
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/user/exception/UserAddressErrorCode.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/user/exception/UserAddressException.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/user/repository/UserAddressRepository.java
Labels: 🐞 BugFix

#72 ✨ [Feat] 장바구니아이템 구현
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/cartitem/controller/CartItemController.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/cartitem/converter/CartItemConverter.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/cartitem/dto/CartItemRequestDTO.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/cartitem/dto/CartItemResponseDTO.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/cartitem/entity/CartItem.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/cartitem/repository/CartItemRepository.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/cartitem/service/command/CartItemCommandService.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/cartitem/service/query/CartItemQueryService.java
Labels: ✨ Feature
