Repository goorm-engineers4/people_of_delivery, pull requests merged in 2025-08, with the labels that each got.

#76 ✨ [FEAT] 리뷰 커서 페이지네이션 적용
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/review/controller/ReviewController.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/review/converter/ReviewConverter.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/review/dto/ReviewResponseDTO.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/review/repository/ReviewRepository.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/review/service/command/ReviewCommandServiceImpl.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/review/service/query/ReviewQueryServiceImpl.java
Labels: ✨ Feature

#80 ✨ [FEAT] Security 설정
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/user/controller/UserController.java
  src/main/java/com/example/cloudfour/peopleofdelivery/global/auth/config/SecurityConfig.java
  src/main/java/com/example/cloudfour/peopleofdelivery/global/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/example/cloudfour/peopleofdelivery/global/auth/jwt/JwtTokenProvider.java
  src/main/java/com/example/cloudfour/peopleofdelivery/global/auth/userdetails/CustomUserDetails.java
Labels: ✨ Feature

#73 ✨ [FEAT] 가게 엔티티 구현
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/store/controller/StoreController.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/store/converter/StoreConverter.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/store/dto/StoreRequestDTO.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/store/dto/StoreResponseDTO.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/store/entity/Store.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/store/repository/StoreRepository.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/store/service/command/StoreCommandService.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/store/service/query/StoreQueryService.java
  src/test/java/com/example/cloudfour/peopleofdelivery/domain/store/service/command/StoreCommandServiceTest.java
Labels: ✨ Feature, 🔨 Refactor

#68 ✨ [FEAT] 메뉴 TDD 구현
  build.gradle
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/controller/MenuController.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/dto/MenuResponseDTO.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/entity/Menu.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/repository/MenuCategoryRepository.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/repository/MenuOptionRepository.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/repository/MenuRepository.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/service/command/MenuCommandServiceImpl.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/service/query/MenuQueryServiceImpl.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/store/repository/StoreRepository.java
  src/test/java/com/example/cloudfour/peopleofdelivery/domain/menu/service/command/MenuCommandServiceImplTest.java
  src/test/java/com/example/cloudfour/peopleofdelivery/domain/menu/service/query/MenuQueryServiceImplTest.java
  src/test/java/com/example/cloudfour/peopleofdelivery/domain/useraddress/entity/UserAddressTest.java
Labels: ✨ Feature

#91 🔨[REFACTOR] 테스트 목데이터 위치 변경
  src/test/java/com/example/cloudfour/peopleofdelivery/fixtures/Factory.java
  src/test/java/com/example/cloudfour/peopleofdelivery/unit/domain/menu/service/command/MenuCommandServiceImplTest.java
  src/test/java/com/example/cloudfour/peopleofdelivery/unit/domain/menu/service/query/MenuQueryServiceImplTest.java
  src/test/java/com/example/cloudfour/peopleofdelivery/unit/domain/store/service/command/StoreCommandServiceTest.java
Labels: 🔨 Refactor

#97 🔨[REFACTOR] 장바구니, 장바구니 아이템 Annotation, Import 수정
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/cart/controller/CartController.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/cart/converter/CartConverter.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/cart/entity/Cart.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/cart/service/command/CartCommandService.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/cartitem/controller/CartItemController.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/cartitem/entity/CartItem.java
Labels: 🔨 Refactor

#96 🔨 [REFACTOR] 메뉴 엔티티 import 문 정리 및 코드 주석 제거
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/controller/MenuController.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/converter/MenuConverter.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/dto/MenuRequestDTO.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/dto/MenuResponseDTO.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/entity/Menu.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/entity/MenuCategory.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/entity/MenuOption.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/repository/MenuCategoryRepository.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/repository/MenuOptionRepository.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/repository/MenuRepository.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/service/command/MenuCommandServiceImpl.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/service/query/MenuQueryServiceImpl.java
Labels: 🔨 Refactor

#93 🔨 [REFACTOR] Store 엔티티 코드 주석제거 및 import문 .*제거
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/store/controller/StoreController.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/store/converter/StoreConverter.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/store/dto/StoreRequestDTO.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/store/dto/StoreResponseDTO.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/store/entity/Store.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/store/entity/StoreCategory.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/store/repository/StoreRepository.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/store/service/command/StoreCommandService.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/store/service/query/StoreQueryService.java
Labels: 🔨 Refactor

#102 🐛 [FIX] Factory 코드 수정
  src/test/java/com/example/cloudfour/peopleofdelivery/fixtures/Factory.java
Labels: 🐞 BugFix

#100 🔨 [REFACTOR] : Store엔티티 name 필드 수정
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/store/entity/Store.java
Labels: 🔨 Refactor

#103 :sparkles: [FEAT] 주문 생성 기능 변경, 추가
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/converter/MenuOptionConverter.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/dto/MenuOptionResponseDTO.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/order/controller/OrderController.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/order/converter/OrderConverter.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/order/converter/OrderItemConverter.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/order/dto/OrderItemResponseDTO.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/order/dto/OrderRequestDTO.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/order/dto/OrderResponseDTO.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/order/service/command/OrderCommandServiceImpl.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/order/service/query/OrderQueryServiceImpl.java
Labels: ✨ Feature

#106 ✨ [FEAT] 가게 기능 디벨롭
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/store/controller/StoreController.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/store/converter/StoreCategoryConverter.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/store/dto/StoreRequestDTO.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/store/dto/StoreResponseDTO.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/store/entity/Store.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/store/entity/StoreCategory.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/store/repository/StoreCategoryRepository.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/store/repository/StoreRepository.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/store/service/command/StoreCommandService.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/store/service/query/StoreQueryService.java
Labels: ✨ Feature

#115 ✨ [FEAT] 장바구니,장바구니 아이템 기능 디벨롭
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/cart/controller/CartController.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/cart/repository/CartRepository.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/cart/service/command/CartCommandService.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/cart/service/query/CartQueryService.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/cartitem/controller/CartItemController.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/cartitem/converter/CartItemConverter.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/cartitem/dto/CartItemRequestDTO.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/cartitem/dto/CartItemResponseDTO.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/cartitem/entity/CartItem.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/cartitem/repository/CartItemRepository.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/cartitem/service/command/CartItemCommandService.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/cartitem/service/query/CartItemQueryService.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/converter/MenuConverter.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/dto/MenuResponseDTO.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/service/query/MenuQueryServiceImpl.java
Labels: ✨ Feature

#114 ✨ [FEAT] 메뉴 옵션 기능 추가
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/controller/MenuController.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/dto/MenuOptionResponseDTO.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/dto/MenuRequestDTO.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/dto/MenuResponseDTO.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/entity/MenuCategory.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/entity/MenuOption.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/repository/MenuOptionRepository.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/repository/MenuRepository.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/service/command/MenuCommandServiceImpl.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/service/query/MenuQueryServiceImpl.java
  src/test/java/com/example/cloudfour/peopleofdelivery/unit/domain/menu/service/command/MenuCommandServiceImplTest.java
  src/test/java/com/example/cloudfour/peopleofdelivery/unit/domain/menu/service/query/MenuQueryServiceImplTest.java
Labels: ✨ Feature

#118 :bug: fix: 메뉴 옵션 빌드 오류 해결
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/dto/MenuRequestDTO.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/entity/MenuCategory.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/menu/service/command/MenuCommandServiceImpl.java
Labels: 🐞 BugFix

#120 🧪 [TEST] 장바구니 TDD 구현
  build.gradle
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/cart/repository/CartRepository.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/user/entity/User.java
  src/main/java/com/example/cloudfour/peopleofdelivery/global/auth/service/AuthService.java
  src/test/java/com/example/cloudfour/peopleofdelivery/unit/domain/cart/repository/CartRepositoryTest.java
  src/test/java/com/example/cloudfour/peopleofdelivery/unit/domain/cart/service/command/CartCommandServiceTest.java
  src/test/java/com/example/cloudfour/peopleofdelivery/unit/domain/cart/service/query/CartQueryServiceTest.java
Labels: ✨ Feature

#125 🐛 [FIX] 메뉴 테스트 실패 문제 해결(Factory 수정)
  src/test/java/com/example/cloudfour/peopleofdelivery/fixtures/Factory.java
Labels: 🐞 BugFix

#124 🔨 Refactor : isdeleted 삭제
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/user/repository/UserRepository.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/user/service/UserService.java
  src/main/java/com/example/cloudfour/peopleofdelivery/global/auth/dto/TokenDto.java
  src/main/java/com/example/cloudfour/peopleofdelivery/global/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/example/cloudfour/peopleofdelivery/global/auth/jwt/JwtTokenProvider.java
  src/main/java/com/example/cloudfour/peopleofdelivery/global/auth/oauth/CustomOAuth2UserService.java
  src/main/java/com/example/cloudfour/peopleofdelivery/global/auth/service/AuthService.java
  src/main/java/com/example/cloudfour/peopleofdelivery/global/auth/service/JpaUserDetailsService.java
  src/main/java/com/example/cloudfour/peopleofdelivery/global/auth/service/OAuthService.java
Labels: 🐞 BugFix, 🔨 Refactor

#134 🧪 [TEST] 장바구니아이템 테스트 코드 구현
  src/test/java/com/example/cloudfour/peopleofdelivery/unit/domain/cartitem/repository/CartItemRepositoryTest.java
  src/test/java/com/example/cloudfour/peopleofdelivery/unit/domain/cartitem/service/command/CartItemCommandServiceTest.java
  src/test/java/com/example/cloudfour/peopleofdelivery/unit/domain/cartitem/service/query/CartItemQueryServiceTest.java
Labels: ✨ Feature

#142 🐛 [FIX] toss 연동 오류 수정
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/payment/apiclient/TossApiClient.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/payment/controller/PaymentController.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/payment/dto/PaymentRequestDTO.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/payment/dto/PaymentResponseDTO.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/payment/dto/TossApproveResponse.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/payment/dto/TossCancelResponse.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/payment/dto/TossErrorResponse.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/payment/dto/TossWebhookPayload.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/payment/entity/Payment.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/payment/enums/PaymentStatus.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/payment/exception/PaymentErrorCode.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/payment/exception/PaymentHistoryErrorCode.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/payment/exception/PaymentHistoryException.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/payment/repository/PaymentRepository.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/payment/service/command/PaymentCommandService.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/payment/service/command/PaymentCommandServiceImpl.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/payment/service/query/PaymentQueryServiceImpl.java
  src/main/resources/application.yml
Labels: 🐞 BugFix, 🔨 Refactor

#145 🔨 [REFACTORY] Factory 메소드 이름 변경에 따른 StoreRepositoryTest 메소드 이름 수정
  src/test/java/com/example/cloudfour/peopleofdelivery/unit/domain/store/repository/StoreRepositoryTest.java
Labels: 🔨 Refactor

#147 🔨 [REFACTOR] user, auth 수정사항 반영
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/user/controller/UserController.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/user/dto/UserRequestDTO.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/user/dto/UserResponseDTO.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/user/entity/User.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/user/entity/UserAddress.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/user/enums/LoginType.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/user/repository/UserRepository.java
  src/main/java/com/example/cloudfour/peopleofdelivery/domain/user/service/UserAddressService.java
  src/main/java/com/example/cloudfour/peopleofdelivery/global/auth/config/SecurityConfig.java
  src/main/java/com/example/cloudfour/peopleofdelivery/global/auth/controller/AuthController.java
  src/main/java/com/example/cloudfour/peopleofdelivery/global/auth/controller/OAuthController.java
  src/main/java/com/example/cloudfour/peopleofdelivery/global/auth/dto/AuthRequestDTO.java
  src/main/java/com/example/cloudfour/peopleofdelivery/global/auth/dto/AuthResponseDTO.java
  src/main/java/com/example/cloudfour/peopleofdelivery/global/auth/dto/OAuthRequestDTO.java
  src/main/java/com/example/cloudfour/peopleofdelivery/global/auth/entity/VerificationCode.java
  src/main/java/com/example/cloudfour/peopleofdelivery/global/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/example/cloudfour/peopleofdelivery/global/auth/jwt/JwtTokenProvider.java
  src/main/java/com/example/cloudfour/peopleofdelivery/global/auth/oauth/CustomOAuth2UserService.java
  src/main/java/com/example/cloudfour/peopleofdelivery/global/auth/oauth/OAuth2SuccessHandler.java
  src/main/java/com/example/cloudfour/peopleofdelivery/global/auth/service/AuthService.java
  src/main/java/com/example/cloudfour/peopleofdelivery/global/auth/service/JpaUserDetailsService.java
  src/main/java/com/example/cloudfour/peopleofdelivery/global/auth/service/OAuthService.java
  src/main/java/com/example/cloudfour/peopleofdelivery/global/auth/userdetails/CustomUserDetails.java
  src/main/java/com/example/cloudfour/peopleofdelivery/global/config/RestClientConfig.java
  src/main/java/com/example/cloudfour/peopleofdelivery/global/entity/BaseEntity.java
Labels: 🔨 Refactor
